SELECT A.TABLESPACE_NAME,
       NVL(ROUND(((C.BYTES - NVL(B.BYTES, 0)) / C.BYTES) * 100, 2), 0) PERCENT_USED,
       ROUND(((C.BYTES - NVL(B.BYTES, 0)) / C.BYTES) * 100, 2) PCT_USED,
       C.BYTES / 1024 / 1024 ALLOCATED_MB,
       ROUND(C.BYTES / 1024 / 1024 - NVL(B.BYTES, 0) / 1024 / 1024, 2) USED_MB
       -- ROUND(NVL(B.BYTES, 0) / 1024 / 1024, 2) FREE_MB,
       -- C.DATAFILES
  FROM DBA_TABLESPACES A,
       (SELECT TABLESPACE_NAME, SUM(BYTES) BYTES
          FROM DBA_FREE_SPACE
         GROUP BY TABLESPACE_NAME) B,
       (SELECT COUNT(1) DATAFILES, SUM(BYTES) BYTES, TABLESPACE_NAME
          FROM DBA_DATA_FILES
         GROUP BY TABLESPACE_NAME) C
WHERE B.TABLESPACE_NAME(+) = A.TABLESPACE_NAME
   AND C.TABLESPACE_NAME(+) = A.TABLESPACE_NAME
ORDER BY NVL(((C.BYTES - NVL(B.BYTES, 0)) / C.BYTES), 0) DESC;
