#!/bin/bash

source /home/oracle/.bash_profile

$ORACLE_HOME/bin/sqlplus / AS SYSDBA <<EOF

EXEC DBMS_STATS.GATHER_DATABASE_STATS(OPTIONS=>'GATHER STALE', CASCADE=>TRUE, NO_INVALIDATE=>FALSE, GATHER_SYS=>FALSE);
EXEC DBMS_STATS.GATHER_DATABASE_STATS(OPTIONS=>'GATHER EMPTY', CASCADE=>TRUE, NO_INVALIDATE=>FALSE, GATHER_SYS=>FALSE);
EXIT;

EOF
