#!/bin/bash

source /home/oracle/.bash_profile

$ORACLE_HOME/bin/sqlplus / AS SYSDBA <<EOF

EXEC DBMS_STATS.GATHER_FIXED_OBJECTS_STATS;
EXEC DBMS_STATS.GATHER_DICTIONARY_STATS(OPTIONS=>'GATHER STALE');
EXEC DBMS_STATS.GATHER_DICTIONARY_STATS(OPTIONS=>'GATHER EMPTY');

EXIT;

EOF
