SET PAGESIZE 1000;
SET LINESIZE 300;
COL EVENT FORMAT A30;
COL SQL_TEXT FORMAT A70;
COL SECONDS_IN_WAIT FORMAT 999

-- 10g ou >
SELECT W.SID, W.EVENT, W.SECONDS_IN_WAIT, SQL.SQL_TEXT FROM GV$SESSION_WAIT W, GV$SESSION S, GV$PROCESS P, GV$SQLTEXT SQL WHERE W.SID = S.SID AND S.PADDR = P.ADDR AND SQL.ADDRESS = S.SQL_ADDRESS AND SQL.HASH_VALUE = S.SQL_HASH_VALUE AND W.WAIT_CLASS != 'Idle' AND W.INST_ID = S.INST_ID AND W.INST_ID = P.INST_ID AND W.INST_ID = SQL.INST_ID ORDER BY W.SECONDS_IN_WAIT, W.SID, SQL.PIECE;

-- 9i
-- SELECT W.SID, W.EVENT, W.SECONDS_IN_WAIT, SQL.SQL_TEXT FROM V$SESSION_WAIT W, V$SESSION S, V$PROCESS P, V$SQLTEXT SQL WHERE W.SID = S.SID AND S.PADDR = P.ADDR AND SQL.ADDRESS = S.SQL_ADDRESS AND SQL.HASH_VALUE = S.SQL_HASH_VALUE AND W.EVENT NOT IN ('smon timer', 'pmon timer') AND W.INST_ID = S.INST_ID AND W.INST_ID = P.INST_ID AND W.INST_ID = SQL.INST_ID ORDER BY W.SECONDS_IN_WAIT, W.SID, SQL.PIECE;


