SET PAGESIZE 1000;
SET LINESIZE 210;
COL EVENT FORMAT A80;

CREATE TABLE PRE_SYSTEM_EVENT AS SELECT * FROM V$SYSTEM_EVENT;
EXECUTE DBMS_LOCK.SLEEP(60);
CREATE TABLE POS_SYSTEM_EVENT AS SELECT * FROM V$SYSTEM_EVENT;

SELECT A.EVENT, A.TIME_WAITED, B.TIME_WAITED, (B.TIME_WAITED-A.TIME_WAITED) DIFF
FROM PRE_SYSTEM_EVENT A, POS_SYSTEM_EVENT B
WHERE A.EVENT = B.EVENT
AND A.TIME_WAITED IS NOT NULL
AND ((B.TIME_WAITED-A.TIME_WAITED) > 0)
AND A.WAIT_CLASS != 'Idle'
ORDER BY DIFF;

DROP TABLE PRE_SYSTEM_EVENT;
DROP TABLE POS_SYSTEM_EVENT;
